# Generated by Django 5.1.7 on 2025-04-21 14:23

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_guest_address_order_guest_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=orders.models.generate_unique_order_code, editable=False, max_length=30, unique=True),
        ),
    ]
